# Generated by Django 6.0.7 on 2026-08-11 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='concluded',
            field=models.BooleanField(default=False),
        ),
    ]
