# Generated by Django 6.0.7 on 2026-08-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0002_alter_task_concluded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=800),
        ),
    ]
